networks:
  oikono:
    name: oikono
  backend:
    name: backend
    external: true

services:
  oikono.api.green:
    container_name: oikono.api.green
    image: ghcr.io/ykoellmann/oikono.api:arm64
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=postgres;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
      - ConnectionStrings__Redis=redis:6379
      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
      - JwtSettings__ExpiryMinutes=10
      - JwtSettings__Issuer=Oikono
      - JwtSettings__Audience=Oikono  
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1__Name=WithProperty
      - Serilog__Enrich__1__Args__name=MachineName
      - Serilog__Enrich__1__Args__value=${HOSTNAME}
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=File
      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
      - Serilog__WriteTo__1__Args__path=/var/logs/log.txt
      - Serilog__WriteTo__1__Args__rollingInterval=Day
      - Serilog__WriteTo__2__Name=Seq
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
      - Serilog__Enrich__2__Name=WithProperty
      - Serilog__Enrich__2__Args__name=Application
      - Serilog__Enrich__2__Args__value=Oikono
    ports:
      - 8100:80
    networks:
      - oikono
      - backend
    restart: unless-stopped
    volumes:
      - logdata:/var/logs
#  oikono.api.blue:
#    container_name: oikono.api.blue
#    image: oikono.api
#    build:
#      context: .
#      dockerfile: src/Oikono.Api/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://*:80
#      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=applepi-db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
#      - ConnectionStrings__Redis=redis-stack:6379
#      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
#      - JwtSettings__ExpiryMinutes=10
#      - JwtSettings__Issuer=Oikono
#      - JwtSettings__Audience=Oikono  - Serilog__MinimumLevel__Override__Microsoft=Warning
#      - Serilog__MinimumLevel__Override__System=Warning
#      - Serilog__Enrich__0=FromLogContext
#      - Serilog__Enrich__1__Name=WithProperty
#      - Serilog__Enrich__1__Args__name=MachineName
#      - Serilog__Enrich__1__Args__value=${HOSTNAME}
#      - Serilog__WriteTo__0__Name=Console
#      - Serilog__WriteTo__1__Name=File
#      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
#      - Serilog__WriteTo__1__Args__path=/var/logs/log.txt
#      - Serilog__WriteTo__1__Args__rollingInterval=Day
#      - Serilog__WriteTo__2__Name=Seq
#      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
#      - Serilog__Enrich__2__Name=WithProperty
#      - Serilog__Enrich__2__Args__name=Application
#      - Serilog__Enrich__2__Args__value=Oikono
#    ports:
#      - 8100:80
#    networks:
#      - oikono-backend
#      - backend
#    volumes:
#      - logdata:/var/logs
#  oikono.api.white:
#    container_name: oikono.api.white
#    image: oikono.api
#    build:
#      context: .
#      dockerfile: src/Oikono.Api/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://*:80
#      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=applepi-db;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
#      - ConnectionStrings__Redis=redis-stack:6379
#      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
#      - JwtSettings__ExpiryMinutes=10
#      - JwtSettings__Issuer=Oikono
#      - JwtSettings__Audience=Oikono  - Serilog__MinimumLevel__Override__Microsoft=Warning
#      - Serilog__MinimumLevel__Override__System=Warning
#      - Serilog__Enrich__0=FromLogContext
#      - Serilog__Enrich__1__Name=WithProperty
#      - Serilog__Enrich__1__Args__name=MachineName
#      - Serilog__Enrich__1__Args__value=${HOSTNAME}
#      - Serilog__WriteTo__0__Name=Console
#      - Serilog__WriteTo__1__Name=File
#      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
#      - Serilog__WriteTo__1__Args__path=/var/logs/log.txt
#      - Serilog__WriteTo__1__Args__rollingInterval=Day
#      - Serilog__WriteTo__2__Name=Seq
#      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
#      - Serilog__Enrich__2__Name=WithProperty
#      - Serilog__Enrich__2__Args__name=Application
#      - Serilog__Enrich__2__Args__value=Oikono
#    ports:
#      - 8100:80
#    networks:
#      - oikono-backend
#      - backend
#    volumes:
#      - logdata:/var/logs
  oikono.loadbalancer:
    container_name: oikono.loadbalancer
    image: ghcr.io/ykoellmann/oikono.loadbalancer:arm64
    restart: unless-stopped
    ports:
#      - "${ADDRESS}:8001:80"
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - ReverseProxy__Clusters__api__Destinations__green__Address=http://oikono.api.green:80
#      - ReverseProxy__Clusters__api__Destinations__blue__Address=http://oikono.api.blue:80
#      - ReverseProxy__Clusters__api__Destinations__white__Address=http://oikono.api.white:80
      - ReverseProxy__Clusters__api__LoadBalancingPolicy=RoundRobin
      - ReverseProxy__Routes__api__ClusterId=api
      - ReverseProxy__Routes__api__Match__Path={**catch-all}
      - ConnectionStrings__DbConnection=User Id=postgres;Password=postgres;Server=postgres;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
      - ConnectionStrings__Redis=redis:6379
      - JwtSettings__Secret=0ba697edfae041c1c756547c88f737db379231f94cf1f89092698877d87e54a2
      - JwtSettings__ExpiryMinutes=10
      - JwtSettings__Issuer=Oikono
      - JwtSettings__Audience=Oikono
    depends_on:
      - oikono.api.green
#      - oikono.api.blue
#      - oikono.api.white
    networks:
      - oikono

volumes:
  appdata:
  logdata:
    driver: local