// <auto-generated />

using System;
using Oikono.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Oikono.Infrastructure.Migrations
{
    [DbContext(typeof(OikonoDbContext))]
    [Migration("20240126164821_AddAuth4")]
    partial class AddAuth4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Oikono")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oikono.Domain.Users.Permission", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 623, DateTimeKind.Utc).AddTicks(1782))
                    .HasColumnOrder(102);

                b.Property<string>("Feature")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 623, DateTimeKind.Utc).AddTicks(2135))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.HasIndex("Feature", "Name")
                    .IsUnique();

                b.ToTable("Permission", "Oikono");

                b.HasData(
                    new
                    {
                        Id = new Guid("f563a999-f5ec-4b42-b9b1-606ef9eb7e1e"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Feature = "Example",
                        Name = "Example:Get",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    },
                    new
                    {
                        Id = new Guid("5a49862e-9f5e-413f-acc5-10257cba195e"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Feature = "Example",
                        Name = "Example:Set",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Oikono.Domain.Users.Policy", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 624, DateTimeKind.Utc).AddTicks(1321))
                    .HasColumnOrder(102);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 624, DateTimeKind.Utc).AddTicks(1649))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Policy", "Oikono");

                b.HasData(
                    new
                    {
                        Id = new Guid("8c442f17-8310-4744-9d27-9bc841eae44f"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "SelfOrAdmin",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Oikono.Domain.Users.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 624, DateTimeKind.Utc).AddTicks(8874))
                    .HasColumnOrder(102);

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnOrder(101);

                b.Property<bool>("Disabled")
                    .HasColumnType("boolean");

                b.Property<DateTime>("Expires")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 625, DateTimeKind.Utc).AddTicks(812))
                    .HasColumnOrder(104);

                b.Property<Guid>("UpdatedBy")
                    .HasColumnType("uuid")
                    .HasColumnOrder(103);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("CreatedBy");

                b.HasIndex("UpdatedBy");

                b.HasIndex("UserId");

                b.ToTable("RefreshToken", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.Role", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 630, DateTimeKind.Utc).AddTicks(6766))
                    .HasColumnOrder(102);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 630, DateTimeKind.Utc).AddTicks(7046))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.ToTable("Role", "Oikono");

                b.HasData(
                    new
                    {
                        Id = new Guid("f02883cc-4715-477a-9b87-7ccd28a90d52"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Admin",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Oikono.Domain.Users.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<bool>("Active")
                    .HasColumnType("boolean");

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 630, DateTimeKind.Utc).AddTicks(9738))
                    .HasColumnOrder(102);

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 631, DateTimeKind.Utc).AddTicks(106))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.ToTable("User", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPermission", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 631, DateTimeKind.Utc).AddTicks(7761))
                    .HasColumnOrder(102);

                b.Property<Guid>("PermissionId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 631, DateTimeKind.Utc).AddTicks(8440))
                    .HasColumnOrder(104);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasAlternateKey("UserId", "PermissionId");

                b.HasIndex("PermissionId");

                b.ToTable("UserPermission", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPolicy", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 633, DateTimeKind.Utc).AddTicks(3526))
                    .HasColumnOrder(102);

                b.Property<Guid>("PolicyId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 633, DateTimeKind.Utc).AddTicks(4048))
                    .HasColumnOrder(104);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasAlternateKey("UserId", "PolicyId");

                b.HasIndex("PolicyId");

                b.ToTable("UserPolicy", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserRole", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 635, DateTimeKind.Utc).AddTicks(9671))
                    .HasColumnOrder(102);

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 26, 16, 48, 21, 636, DateTimeKind.Utc).AddTicks(357))
                    .HasColumnOrder(104);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasAlternateKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("UserRole", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.RefreshToken", b =>
            {
                b.HasOne("Oikono.Domain.Users.User", "CreatedByUser")
                    .WithMany()
                    .HasForeignKey("CreatedBy")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "UpdatedByUser")
                    .WithMany()
                    .HasForeignKey("UpdatedBy")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CreatedByUser");

                b.Navigation("UpdatedByUser");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPermission", b =>
            {
                b.HasOne("Oikono.Domain.Users.Permission", "Permission")
                    .WithMany("UserPermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("UserPermissions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Permission");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPolicy", b =>
            {
                b.HasOne("Oikono.Domain.Users.Policy", "Policy")
                    .WithMany("UserPolicies")
                    .HasForeignKey("PolicyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("UserPolicies")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Policy");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserRole", b =>
            {
                b.HasOne("Oikono.Domain.Users.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.Permission", b => { b.Navigation("UserPermissions"); });

            modelBuilder.Entity("Oikono.Domain.Users.Policy", b => { b.Navigation("UserPolicies"); });

            modelBuilder.Entity("Oikono.Domain.Users.Role", b => { b.Navigation("UserRoles"); });

            modelBuilder.Entity("Oikono.Domain.Users.User", b =>
            {
                b.Navigation("RefreshTokens");

                b.Navigation("UserPermissions");

                b.Navigation("UserPolicies");

                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}