// <auto-generated />

using System;
using Oikono.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Oikono.Infrastructure.Migrations
{
    [DbContext(typeof(OikonoDbContext))]
    [Migration("20240128130705_AddAuth6")]
    partial class AddAuth6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Oikono")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oikono.Domain.Users.Permission", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 273, DateTimeKind.Utc).AddTicks(8366))
                    .HasColumnOrder(102);

                b.Property<string>("Feature")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 273, DateTimeKind.Utc).AddTicks(8757))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.HasIndex("Feature", "Name")
                    .IsUnique();

                b.ToTable("Permission", "Oikono");

                b.HasData(
                    new
                    {
                        Id = new Guid("d1dbccbf-56d5-4698-b2ff-c5df8b88358f"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Feature = "WeatherForecast",
                        Name = "WeatherForecast:Get",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    },
                    new
                    {
                        Id = new Guid("9dbe241f-884a-485d-8dc6-4d183b5e701a"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Feature = "WeatherForecast",
                        Name = "WeatherForecast:Set",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    },
                    new
                    {
                        Id = new Guid("ee51430f-4c62-4013-8c67-8c4faf4710ba"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Feature = "WeatherForecast",
                        Name = "WeatherForecast:Delete",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Oikono.Domain.Users.Policy", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 274, DateTimeKind.Utc).AddTicks(9223))
                    .HasColumnOrder(102);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 274, DateTimeKind.Utc).AddTicks(9545))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Policy", "Oikono");

                b.HasData(
                    new
                    {
                        Id = new Guid("22b96710-484c-4df9-86da-d62f30a689d2"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "SelfOrAdmin",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Oikono.Domain.Users.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 275, DateTimeKind.Utc).AddTicks(7658))
                    .HasColumnOrder(102);

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("uuid")
                    .HasColumnOrder(101);

                b.Property<bool>("Disabled")
                    .HasColumnType("boolean");

                b.Property<DateTime>("Expires")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 275, DateTimeKind.Utc).AddTicks(9826))
                    .HasColumnOrder(104);

                b.Property<Guid>("UpdatedBy")
                    .HasColumnType("uuid")
                    .HasColumnOrder(103);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("CreatedBy");

                b.HasIndex("UpdatedBy");

                b.HasIndex("UserId");

                b.ToTable("RefreshToken", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.Role", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 283, DateTimeKind.Utc).AddTicks(8663))
                    .HasColumnOrder(102);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 283, DateTimeKind.Utc).AddTicks(9183))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.ToTable("Role", "Oikono");

                b.HasData(
                    new
                    {
                        Id = new Guid("d6717309-622e-4577-98ae-1fc68fd157c3"),
                        CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Admin",
                        UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                    });
            });

            modelBuilder.Entity("Oikono.Domain.Users.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<bool>("Active")
                    .HasColumnType("boolean");

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 284, DateTimeKind.Utc).AddTicks(2860))
                    .HasColumnOrder(102);

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 284, DateTimeKind.Utc).AddTicks(3511))
                    .HasColumnOrder(104);

                b.HasKey("Id");

                b.ToTable("User", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPermission", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 285, DateTimeKind.Utc).AddTicks(6360))
                    .HasColumnOrder(102);

                b.Property<Guid>("PermissionId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 285, DateTimeKind.Utc).AddTicks(7090))
                    .HasColumnOrder(104);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasAlternateKey("UserId", "PermissionId");

                b.HasIndex("PermissionId");

                b.ToTable("UserPermission", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPolicy", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 287, DateTimeKind.Utc).AddTicks(5136))
                    .HasColumnOrder(102);

                b.Property<Guid>("PolicyId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 287, DateTimeKind.Utc).AddTicks(5637))
                    .HasColumnOrder(104);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasAlternateKey("UserId", "PolicyId");

                b.HasIndex("PolicyId");

                b.ToTable("UserPolicy", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserRole", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnOrder(0);

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 289, DateTimeKind.Utc).AddTicks(3153))
                    .HasColumnOrder(102);

                b.Property<Guid>("RoleId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .ValueGeneratedOnUpdate()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValue(new DateTime(2024, 1, 28, 13, 7, 5, 289, DateTimeKind.Utc).AddTicks(3683))
                    .HasColumnOrder(104);

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasAlternateKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("UserRole", "Oikono");
            });

            modelBuilder.Entity("Oikono.Domain.Users.RefreshToken", b =>
            {
                b.HasOne("Oikono.Domain.Users.User", "CreatedByUser")
                    .WithMany()
                    .HasForeignKey("CreatedBy")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "UpdatedByUser")
                    .WithMany()
                    .HasForeignKey("UpdatedBy")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CreatedByUser");

                b.Navigation("UpdatedByUser");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPermission", b =>
            {
                b.HasOne("Oikono.Domain.Users.Permission", "Permission")
                    .WithMany("UserPermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("UserPermissions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Permission");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserPolicy", b =>
            {
                b.HasOne("Oikono.Domain.Users.Policy", "Policy")
                    .WithMany("UserPolicies")
                    .HasForeignKey("PolicyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("UserPolicies")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Policy");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.UserRole", b =>
            {
                b.HasOne("Oikono.Domain.Users.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Oikono.Domain.Users.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

            modelBuilder.Entity("Oikono.Domain.Users.Permission", b => { b.Navigation("UserPermissions"); });

            modelBuilder.Entity("Oikono.Domain.Users.Policy", b => { b.Navigation("UserPolicies"); });

            modelBuilder.Entity("Oikono.Domain.Users.Role", b => { b.Navigation("UserRoles"); });

            modelBuilder.Entity("Oikono.Domain.Users.User", b =>
            {
                b.Navigation("RefreshTokens");

                b.Navigation("UserPermissions");

                b.Navigation("UserPolicies");

                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
        }
    }
}